name: launcher_entry
description: A wrapper around the Unity LauncherAPI.
version: 0.1.0
repository: https://github.com/canonical/launcher_entry
issue_tracker: https://github.com/canonical/launcher_entry/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.17.0"

platforms:
  linux:

dependencies:
  dbus: ^0.7.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: